name: oxidized
description: Definitions of Rust-like types, Option and Result, to promote safer programming.
version: 5.3.1
homepage: https://github.com/nlfiedler/oxidized
repository: https://github.com/nlfiedler/oxidized.git
issue_tracker: https://github.com/nlfiedler/oxidized/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.20.1
  very_good_analysis: ^3.1.0
