name: oxidized
description: Definitions of Rust-like types, Option and Result, to promote safer programming.
version: 5.2.0
homepage: https://github.com/nlfiedler/oxidized
repository: https://github.com/nlfiedler/oxidized.git
issue_tracker: https://github.com/nlfiedler/oxidized/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
