name: oxidized
description: Definitions of the Rust-like types, Option and Result, to promote safer programming.
version: 3.1.0
homepage: https://github.com/nlfiedler/oxidized
repository: https://github.com/nlfiedler/oxidized.git
issue_tracker: https://github.com/nlfiedler/oxidized/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  equatable: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
